services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: react-component-studio:local
    container_name: react-component-studio
    ports:
      - "8080:80"

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:1.3.0
    container_name: react-component-studio-exporter
    command:
      - "-nginx.scrape-uri=http://app/nginx_status"
    depends_on:
      - app
    ports:
      - "9113:9113"

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: react-component-studio-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - nginx-exporter
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:11.1.0
    container_name: react-component-studio-grafana
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    volumes:
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards:ro
    ports:
      - "3000:3000"
