apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: react-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: react-app
  endpoints:
    - port: http
      path: /metrics
      interval: 5s