apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: react-component-studio
  namespace: react-studio
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: react-component-studio
  namespaceSelector:
    matchNames:
      - react-studio
  endpoints:
    - port: metrics
      interval: 15s
      path: /metrics
